### ISSUE TITLE
Milestone-2

### ISSUE THREAD

**Issue by akanshaVashisth** [UBC-MDS/filterizePy#21]
- [x] create a branch
- [x] work on the function you are responsible for in this branch
- [x] add commits
- [x] open a pull request (you should be at this step by the end of the lab on Feb 12th)
- [x] wait for the code review and feedback from other team member
- [x] review code of other team member via their pull request
- [x] deploy your changes
- [x] merge if your branch is not causing any problems

**Comment by akanshaVashisth** [comment]
Writing function for script color.py

**Comment by chaomander2018** [comment]
- [ ] Check script test comments
- [ ]  Define `sharpen` it would be good to define what exactly it means that the function will "sharpen" an image

- [x] Your test descriptions are good, but it might be useful if you included specific error messages with each of your tests.
