### ISSUE TITLE
ML4 to-do list

### ISSUE THREAD

**Issue by chaomander2018** [UBC-MDS/filterizePy#38]
Hi  team
- [ ] Add appropriate exception handler in Python for all functions.

- [ ] Add adequate integration tests in each package, if applicable. (Ask Rainer)

- [ ] Set up continuous integration testing using Travis and add a passing build stamp for each package README files.

- [ ] In your README, include a clear description of how to install your package and call your functions. Also include an **example** with a **toy dataset** and a **screenshot** of the output when you run tests.

- [ ] Individually report the contributions of each team member by filling out this standard form. This is worth 10% of your grade and is due the morning after the final project submission, i.e., on Sunday, March 10th at noon.
